mode: 'longitudinal'
longitudinal_predict_future: False
sig2e_list:
  - 1.0
sig2bs_identical_list:
  - False
sig2bs_mean_list:
  -
    - 0.3
    - 3.0
  -
    - 0.3
    - 3.0
  -
    - 0.3
    - 3.0
estimated_cors:
  - '01'
  - '02'
beta_list:
  - 0.001
rho_list:
  -
    - 0.3
  -
    - 0.3
sig2b_spatial_list: []
q_list:
  -
    - 100
    - 1000
    - 10000
q_spatial_list: []
latent_dimension_list:
  - 1
  - 2
N_list:
  - 100000
n_iter: 5
n_per_cat: 3
fixed_intercept: 1
n_fixed_features: 100
n_neurons:
  - 1000
  - 500
dropout:
activation: 'relu'
X_non_linear: True
Z_non_linear: False
batch_size: 1000
epochs: 200
patience:
verbose: False
log_params: False
test_size: 0.2
thresh: 0.0001
RE_cols_prefix: 'z'
dr_types:
  - 'pca-ignore'
  - 'pca-ohe'
  - 'vae-ignore'
  - 'vae-ohe'
  - 'vae-embed'
  - 'vrae'
  - 'lmmvae'
  - 'svgpvae-10-16-2'
