sig2e_list:
  - 1.0
sig2bs_identical_list:
  - False
sig2bs_mean_list:
  - 1
  - 0.1
q_list:
  -
    - 100
    - 1000
    - 10000
latent_dimension_list:
  - 2
  - 5
N_list:
  - 100000
n_iter: 5
n_per_cat: 3
fixed_intercept: 1
n_fixed_features: 100
n_neurons:
  - 100
  - 50
  - 20
  - 10
dropout:
activation: 'relu'
X_non_linear: True
Z_non_linear: False
batch_size: 100
epochs: 1000
patience: 10
verbose: False
log_params: False
test_size: 0.2
thresh: 0.0001
RE_col: 'z'
pca_types:
  - 'ignore'
  - 'ohe'
  - 'vae'
  - 'lmmvae'
