mode: 'categorical'
rho_list: []
sig2e_list:
  - 1.0
sig2bs_identical_list:
  - False
sig2bs_mean_list:
  -
    - 0.1
    - 1
    - 10
  -
    - 0.1
    - 1
    - 10
sig2b_spatial_list: []
q_list:
  -
    - 100
    - 1000
    - 10000
  -
    - 100
    - 1000
    - 10000
q_spatial_list: []
latent_dimension_list:
  - 1
  - 2
N_list:
  - 100000
n_iter: 3
n_per_cat: 3
fixed_intercept: 1
n_fixed_features: 100
n_neurons:
  - 1000
  - 500
dropout:
activation: 'relu'
X_non_linear: True
Z_non_linear: False
batch_size: 100
epochs: 1000
patience: 10
verbose: False
log_params: False
test_size: 0.2
thresh: 0.0001
RE_cols_prefix: 'z'
dr_types:
  - 'pca-ignore'
  - 'pca-ohe'
  - 'vae-ohe'
  - 'vae-ignore'
  - 'lmmvae'
