mode: 'spatial'
sig2e_list:
  - 1.0
sig2bs_identical_list:
  - False
sig2bs_mean_list: []
sig2b_spatial_list:
  -
    - 0.1
    - 1.0
    - 10.0
  -
    - 1.0
q_list: []
q_spatial_list:
  - 100
  - 1000
  - 10000
latent_dimension_list:
  - 1
  - 2
N_list:
  - 100000
n_iter: 3
n_per_cat: 3
fixed_intercept: 1
n_fixed_features: 10
n_neurons:
  - 1000
  - 500
dropout:
activation: 'relu'
X_non_linear: True
Z_non_linear: False
batch_size: 100
epochs: 1000
patience: 10
verbose: True
log_params: False
test_size: 0.2
thresh: 0.0001
RE_cols_prefix: 'z'
pca_types:
  - 'ignore'
  - 'ohe'
  - 'vae'
  - 'vae-ignore'
  - 'lmmvae'
